# -*- coding: utf-8 -*-
"""ResearchPaperSmmarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hL1Go8IMlOZfzPqpe0_HyPo-_z52g4mb
"""

!pip install transformers

from transformers import pipeline

!pip install arxiv

import arxiv
import pandas as pd

#query to fetch ai related paper
query='ai or artificial intelligence or machine learning'
search= arxiv.Search(query=query, max_results=10, sort_by=arxiv.SortCriterion.SubmittedDate)

#fetch paper
papers=[]
for result in search.results():
  papers.append({
      'published':result.published,
      'title':result.title,
      'abstract':result.summary,
      'categories':result.categories
  })

df = pd.DataFrame(papers)

pd.set_option('display.max_colwidth', None)
df.head(10)

# example abstract from api
abstract = df['abstract'][0]

summarizer = pipeline("summarization" , model = "facebook/bart-large-cnn")

#summarization
summarization_result = summarizer(abstract)

summarization_result[0]['summary_text']



